In [1]:
from pathlib import Path as ps
# определение пути
def get_files(directory, files=[]):
    currentDirectory = ps(directory)
    for currentFile in currentDirectory.iterdir():
        if currentFile.is_file():
            files.append(currentFile)
    return files # Формирует список Windowpath-объектов

files=get_files('C:\projects\sm-code\shop\EXE2\Images') # Принимает полный адрес директории

NameError: name 'path' is not defined

In [2]:
from PIL import Image
def scale_image(input_image_path,
                output_image_path,
                width=None,
                height=None
                ):
    original_image = Image.open(input_image_path)
    w, h = original_image.size
    print('The original file: '+input_image_path)
    print('The original image size is {wide} wide x {height} '
          'high'.format(wide=w, height=h))
 
    if width and height:
        max_size = (width, height)
    elif width:
        max_size = (width, h)
    elif height:
        max_size = (w, height)
    else:
        # No width or height specified
        raise RuntimeError('Width or height required!')
 
    original_image.thumbnail(max_size, Image.ANTIALIAS)
    original_image.save(output_image_path)
 
    scaled_image = Image.open(output_image_path)
    width, height = scaled_image.size
    print('The scaled file: '+output_image_path)
    print('The scaled image size is {wide} wide x {height} '
          'high'.format(wide=width, height=height))

def make_scaled_images (original_files,new_width=None,new_heght=None,scaled_files=[]):    
    for i in original_files:
        scaled_file=ps(i.parent,i.stem+'2'+i.suffix)
        if __name__ == '__main__':
            scale_image(input_image_path=str(i),
                    output_image_path=str(scaled_file),
                    width=new_width,
                    height=new_heght)
        scaled_files.append(scaled_file)
    return scaled_files

scaled_files=make_scaled_images(files,80) # Принимает список Windowpath-объектов

The original file:C:\projects\sm-code\shop\EXE2\Images\310 Motoring.jpg
The original image size is 136 wide x 62 high
The scaled file:C:\projects\sm-code\shop\EXE2\Images\310 Motoring.jpg
The scaled image size is 80 wide x 36 high
The original file:C:\projects\sm-code\shop\EXE2\Images\Adidas.jpg
The original image size is 765 wide x 348 high
The scaled file:C:\projects\sm-code\shop\EXE2\Images\Adidas.jpg
The scaled image size is 80 wide x 36 high
The original file:C:\projects\sm-code\shop\EXE2\Images\Aquasphere.jpg
The original image size is 317 wide x 61 high
The scaled file:C:\projects\sm-code\shop\EXE2\Images\Aquasphere.jpg
The scaled image size is 80 wide x 15 high
The original file:C:\projects\sm-code\shop\EXE2\Images\Asics.jpg
The original image size is 765 wide x 348 high
The scaled file:C:\projects\sm-code\shop\EXE2\Images\Asics.jpg
The scaled image size is 80 wide x 36 high
The original file:C:\projects\sm-code\shop\EXE2\Images\Caterpillar.jpg
The original image size is 765 wide x 348 high
The scaled file:C:\projects\sm-code\shop\EXE2\Images\Caterpillar.jpg
The scaled image size is 80 wide x 36 high
The original file:C:\projects\sm-code\shop\EXE2\Images\Columbia.jpg
The original image size is 765 wide x 348 high
The scaled file:C:\projects\sm-code\shop\EXE2\Images\Columbia.jpg
The scaled image size is 80 wide x 36 high
The original file:C:\projects\sm-code\shop\EXE2\Images\Crocs.jpg
The original image size is 1475 wide x 615 high
The scaled file:C:\projects\sm-code\shop\EXE2\Images\Crocs.jpg
The scaled image size is 80 wide x 33 high
The original file:C:\projects\sm-code\shop\EXE2\Images\Delamare.jpg
The original image size is 765 wide x 348 high
The scaled file:C:\projects\sm-code\shop\EXE2\Images\Delamare.jpg
The scaled image size is 80 wide x 36 high
The original file:C:\projects\sm-code\shop\EXE2\Images\Demix.jpg
The original image size is 577 wide x 289 high
The scaled file:C:\projects\sm-code\shop\EXE2\Images\Demix.jpg
The scaled image size is 80 wide x 40 high
The original file:C:\projects\sm-code\shop\EXE2\Images\Everlast.jpg
The original image size is 2132 wide x 1460 high
The scaled file:C:\projects\sm-code\shop\EXE2\Images\Everlast.jpg
The scaled image size is 80 wide x 54 high
The original file:C:\projects\sm-code\shop\EXE2\Images\Fila.jpg
The original image size is 833 wide x 270 high
The scaled file:C:\projects\sm-code\shop\EXE2\Images\Fila.jpg
The scaled image size is 80 wide x 25 high
The original file:C:\projects\sm-code\shop\EXE2\Images\Fischer.jpg
The original image size is 575 wide x 633 high
The scaled file:C:\projects\sm-code\shop\EXE2\Images\Fischer.jpg
The scaled image size is 80 wide x 88 high
The original file:C:\projects\sm-code\shop\EXE2\Images\Freddy.jpg
The original image size is 765 wide x 348 high
The scaled file:C:\projects\sm-code\shop\EXE2\Images\Freddy.jpg
The scaled image size is 80 wide x 36 high
The original file:C:\projects\sm-code\shop\EXE2\Images\Helly Hansen.jpg
The original image size is 765 wide x 348 high
The scaled file:C:\projects\sm-code\shop\EXE2\Images\Helly Hansen.jpg
The scaled image size is 80 wide x 36 high
The original file:C:\projects\sm-code\shop\EXE2\Images\Joss.jpg
The original image size is 765 wide x 348 high
The scaled file:C:\projects\sm-code\shop\EXE2\Images\Joss.jpg
The scaled image size is 80 wide x 36 high
The original file:C:\projects\sm-code\shop\EXE2\Images\Kappa.jpg
The original image size is 409 wide x 213 high
The scaled file:C:\projects\sm-code\shop\EXE2\Images\Kappa.jpg
The scaled image size is 80 wide x 41 high
The original file:C:\projects\sm-code\shop\EXE2\Images\Lotto.jpg
The original image size is 375 wide x 135 high
The scaled file:C:\projects\sm-code\shop\EXE2\Images\Lotto.jpg
The scaled image size is 80 wide x 28 high
The original file:C:\projects\sm-code\shop\EXE2\Images\Marc Ecko.jpg
The original image size is 765 wide x 348 high
The scaled file:C:\projects\sm-code\shop\EXE2\Images\Marc Ecko.jpg
The scaled image size is 80 wide x 36 high
The original file:C:\projects\sm-code\shop\EXE2\Images\Merrell.jpg
The original image size is 765 wide x 348 high
The scaled file:C:\projects\sm-code\shop\EXE2\Images\Merrell.jpg
The scaled image size is 80 wide x 36 high
The original file:C:\projects\sm-code\shop\EXE2\Images\Mitre.jpg
The original image size is 765 wide x 348 high
The scaled file:C:\projects\sm-code\shop\EXE2\Images\Mitre.jpg
The scaled image size is 80 wide x 36 high
The original file:C:\projects\sm-code\shop\EXE2\Images\Mizuno.jpg
The original image size is 1024 wide x 576 high
The scaled file:C:\projects\sm-code\shop\EXE2\Images\Mizuno.jpg
The scaled image size is 80 wide x 45 high
The original file:C:\projects\sm-code\shop\EXE2\Images\New Balance.jpg
The original image size is 765 wide x 348 high
The scaled file:C:\projects\sm-code\shop\EXE2\Images\New Balance.jpg
The scaled image size is 80 wide x 36 high
The original file:C:\projects\sm-code\shop\EXE2\Images\Nike.jpg
The original image size is 765 wide x 348 high
The scaled file:C:\projects\sm-code\shop\EXE2\Images\Nike.jpg
The scaled image size is 80 wide x 36 high
The original file:C:\projects\sm-code\shop\EXE2\Images\Nordway.jpg
The original image size is 215 wide x 103 high
The scaled file:C:\projects\sm-code\shop\EXE2\Images\Nordway.jpg
The scaled image size is 80 wide x 38 high
The original file:C:\projects\sm-code\shop\EXE2\Images\North Face.jpg
The original image size is 582 wide x 582 high
The scaled file:C:\projects\sm-code\shop\EXE2\Images\North Face.jpg
The scaled image size is 80 wide x 80 high
The original file:C:\projects\sm-code\shop\EXE2\Images\ONeill.jpg
The original image size is 765 wide x 348 high
The scaled file:C:\projects\sm-code\shop\EXE2\Images\ONeill.jpg
The scaled image size is 80 wide x 36 high
The original file:C:\projects\sm-code\shop\EXE2\Images\Outventure.jpg
The original image size is 765 wide x 348 high
The scaled file:C:\projects\sm-code\shop\EXE2\Images\Outventure.jpg
The scaled image size is 80 wide x 36 high
The original file:C:\projects\sm-code\shop\EXE2\Images\Puma.jpg
The original image size is 765 wide x 348 high
The scaled file:C:\projects\sm-code\shop\EXE2\Images\Puma.jpg
The scaled image size is 80 wide x 36 high
The original file:C:\projects\sm-code\shop\EXE2\Images\Reebok.jpg
The original image size is 765 wide x 348 high
The scaled file:C:\projects\sm-code\shop\EXE2\Images\Reebok.jpg
The scaled image size is 80 wide x 36 high
The original file:C:\projects\sm-code\shop\EXE2\Images\Reima.jpg
The original image size is 1300 wide x 709 high
The scaled file:C:\projects\sm-code\shop\EXE2\Images\Reima.jpg
The scaled image size is 80 wide x 43 high
The original file:C:\projects\sm-code\shop\EXE2\Images\Romika.jpg
The original image size is 237 wide x 126 high
The scaled file:C:\projects\sm-code\shop\EXE2\Images\Romika.jpg
The scaled image size is 80 wide x 42 high
The original file:C:\projects\sm-code\shop\EXE2\Images\Rossignol.jpg
The original image size is 214 wide x 103 high
The scaled file:C:\projects\sm-code\shop\EXE2\Images\Rossignol.jpg
The scaled image size is 80 wide x 38 high
The original file:C:\projects\sm-code\shop\EXE2\Images\Salomon.jpg
The original image size is 765 wide x 348 high
The scaled file:C:\projects\sm-code\shop\EXE2\Images\Salomon.jpg
The scaled image size is 80 wide x 36 high
The original file:C:\projects\sm-code\shop\EXE2\Images\Saucony.jpg
The original image size is 3508 wide x 1890 high
The scaled file:C:\projects\sm-code\shop\EXE2\Images\Saucony.jpg
The scaled image size is 80 wide x 43 high
The original file:C:\projects\sm-code\shop\EXE2\Images\Scubapro.jpg
The original image size is 1159 wide x 527 high
The scaled file:C:\projects\sm-code\shop\EXE2\Images\Scubapro.jpg
The scaled image size is 80 wide x 36 high
The original file:C:\projects\sm-code\shop\EXE2\Images\Skandia.jpg
The original image size is 534 wide x 400 high
The scaled file:C:\projects\sm-code\shop\EXE2\Images\Skandia.jpg
The scaled image size is 80 wide x 59 high
The original file:C:\projects\sm-code\shop\EXE2\Images\Skechers.jpg
The original image size is 765 wide x 348 high
The scaled file:C:\projects\sm-code\shop\EXE2\Images\Skechers.jpg
The scaled image size is 80 wide x 36 high
The original file:C:\projects\sm-code\shop\EXE2\Images\Sorel.jpg
The original image size is 612 wide x 417 high
The scaled file:C:\projects\sm-code\shop\EXE2\Images\Sorel.jpg
The scaled image size is 80 wide x 54 high
The original file:C:\projects\sm-code\shop\EXE2\Images\Speedo.jpg
The original image size is 765 wide x 348 high
The scaled file:C:\projects\sm-code\shop\EXE2\Images\Speedo.jpg
The scaled image size is 80 wide x 36 high
The original file:C:\projects\sm-code\shop\EXE2\Images\Technisub.jpg
The original image size is 268 wide x 119 high
The scaled file:C:\projects\sm-code\shop\EXE2\Images\Technisub.jpg
The scaled image size is 80 wide x 35 high
The original file:C:\projects\sm-code\shop\EXE2\Images\Tecnica.jpg
The original image size is 765 wide x 348 high
The scaled file:C:\projects\sm-code\shop\EXE2\Images\Tecnica.jpg
The scaled image size is 80 wide x 36 high
The original file:C:\projects\sm-code\shop\EXE2\Images\Termit.jpg
The original image size is 156 wide x 75 high
The scaled file:C:\projects\sm-code\shop\EXE2\Images\Termit.jpg
The scaled image size is 80 wide x 38 high
The original file:C:\projects\sm-code\shop\EXE2\Images\timberland.jpg
The original image size is 1089 wide x 495 high
The scaled file:C:\projects\sm-code\shop\EXE2\Images\timberland.jpg
The scaled image size is 80 wide x 36 high
The original file:C:\projects\sm-code\shop\EXE2\Images\tusa.jpg
The original image size is 392 wide x 178 high
The scaled file:C:\projects\sm-code\shop\EXE2\Images\tusa.jpg
The scaled image size is 80 wide x 36 high
The original file:C:\projects\sm-code\shop\EXE2\Images\Umbro.jpg
The original image size is 765 wide x 348 high
The scaled file:C:\projects\sm-code\shop\EXE2\Images\Umbro.jpg
The scaled image size is 80 wide x 36 high
The original file:C:\projects\sm-code\shop\EXE2\Images\Victor.jpg
The original image size is 2604 wide x 394 high
The scaled file:C:\projects\sm-code\shop\EXE2\Images\Victor.jpg
The scaled image size is 80 wide x 12 high
The original file:C:\projects\sm-code\shop\EXE2\Images\View.jpg
The original image size is 526 wide x 173 high
The scaled file:C:\projects\sm-code\shop\EXE2\Images\View.jpg
The scaled image size is 80 wide x 26 high
The original file:C:\projects\sm-code\shop\EXE2\Images\Wilson.jpg
The original image size is 1024 wide x 232 high
The scaled file:C:\projects\sm-code\shop\EXE2\Images\Wilson.jpg
The scaled image size is 80 wide x 18 high
The original file:C:\projects\sm-code\shop\EXE2\Images\Авантаж.jpg
The original image size is 240 wide x 240 high
The scaled file:C:\projects\sm-code\shop\EXE2\Images\Авантаж.jpg
The scaled image size is 80 wide x 80 high

In [3]:
import base64 as bs    
 
def base64_encode_images(images):
    for i in images:
        image_read = i.read_bytes() #open binary file in read mode
        image_64_encode = bs.b64encode(image_read)
        base64=str((image_64_encode))[2:-1]
        filename=(i.stem[:-1])+i.suffix #Отрезаю у нового файла постфикс
        print("""declare
    l_clob      clob;
    l_filename  varchar2(254);
begin  
    l_clob := '"""+base64+"""';
    l_filename := '"""+filename+"""';

    MERGE INTO t_shp_ware_epl_image p
      USING ( SELECT l_clob     as image64
                   , l_filename as filename
                FROM dual
            ) p1 ON ( p.filename = p1.filename )
      WHEN MATCHED THEN UPDATE SET p.image64 = p1.image64
      WHEN NOT MATCHED THEN INSERT ( p.filename , p.image64)
                            VALUES ( p1.filename, p1.image64);
    commit;                            
end;
/
""")
        
base64_encode_images(scaled_files)

declare
    l_clob      clob;
    l_filename  varchar2(254);
begin
    l_clob := '/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDAAgGBgcGBQgHBwcJCQgKDBQNDAsLDBkSEw8UHRofHh0aHBwgJC4nICIsIxwcKDcpLDAxNDQ0Hyc5PTgyPC4zNDL/2wBDAQkJCQwLDBgNDRgyIRwhMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjL/wAARCAAkAFADASIAAhEBAxEB/8QAHwAAAQUBAQEBAQEAAAAAAAAAAAECAwQFBgcICQoL/8QAtRAAAgEDAwIEAwUFBAQAAAF9AQIDAAQRBRIhMUEGE1FhByJxFDKBkaEII0KxwRVS0fAkM2JyggkKFhcYGRolJicoKSo0NTY3ODk6Q0RFRkdISUpTVFVWV1hZWmNkZWZnaGlqc3R1dnd4eXqDhIWGh4iJipKTlJWWl5iZmqKjpKWmp6ipqrKztLW2t7i5usLDxMXGx8jJytLT1NXW19jZ2uHi4+Tl5ufo6erx8vP09fb3+Pn6/8QAHwEAAwEBAQEBAQEBAQAAAAAAAAECAwQFBgcICQoL/8QAtREAAgECBAQDBAcFBAQAAQJ3AAECAxEEBSExBhJBUQdhcRMiMoEIFEKRobHBCSMzUvAVYnLRChYkNOEl8RcYGRomJygpKjU2Nzg5OkNERUZHSElKU1RVVldYWVpjZGVmZ2hpanN0dXZ3eHl6goOEhYaHiImKkpOUlZaXmJmaoqOkpaanqKmqsrO0tba3uLm6wsPExcbHyMnK0tPU1dbX2Nna4uPk5ebn6Onq8vP09fb3+Pn6/9oADAMBAAIRAxEAPwD3+ioriSSOB3hi82QDKx7gu4+mTwK5efxRcJIUa/0G2kBwY2uWmZT6EKBzQB1tFeJ+K/jVqXhfVIrVINI1WN13FrczRlD6HcCM/TNaUfxe1OTwhd+ID4fso47UKWhbVFaRwSBlVVSRjI64oA9aor58tP2j7iXUrdLvQ4LeyMgEzpM0jqmeSBgZNaR/aCfU9Xt9N8P+HHmluZVhia7uAm5mOBwoOPzoA9xorj9Uv/GumaLPqC2miXckEZlkto5JULADJCsc5P1AriPD37Q+i6hcR2+s6fPppcgecjiWIe54BA/A0Aez0U2N1ljV0YMrAEEdCKdQBzXjHULzTdLintNWsdMZp1iMt5bNMhLcKPlI289zxWFo+va6mjXGpz6h4cvLGGR0kuYYp4PmVtpGMNu544654rub3T7TUYPJvLeK4iznZKgZc4I6H2JqJNH06OwksUs4FtJM74RGNjZ9vwFAHnnivS9R+IHhu5tptQ0+0sYJf9J8qylmuI3TDFQGwVPIJwOQfSuCT4I6Unh9tSHiEtb3OwW08tlIrfMwC7YwcsWyAPrX0Ha6ZZ2Vq1tbW0cULElkVeGJ6k+ppJNLspdPWwktomtFVVWEqNoC9AB2xgYoA+do/gjp9tpx1m48VRSWEEuyZXspFO4PsKEBtyndx7Grth8HLS0S38TaX4vW3jiukNs7WTMFkEgUA5IJ+fjpXvS6RYLp4sFtIRaA7vJ2Dbnduzj13c/Wnf2VYi1NsLWHyDJ5pj2Dbv3b92PXdz9aAOH8SajrX2STQLvXdD0+9u4NplS2mZijt5eUUnAJJx1OOtcRp/wY8JeHtXt4/EGtXN/N8r/Z0gMcYBbapkIyQpbjkjNe23Wj6ffSiW7s4J5Bsw0kYYja25fybke9NvtD03Upo5r2yguJI+EaRASOc/zAP1oAuxoscaoihVUYAAwAPSn0gGBS0AFFFFABRRRQAUUUUAFFFFABRRRQB//Z';
    l_filename := '310 Motoring.jpg';

    MERGE INTO t_shp_ware_epl_image p
      USING ( SELECT l_clob     as image64
                   , l_filename as filename
                FROM dual
            ) p1 ON ( p.filename = p1.filename )
      WHEN MATCHED THEN UPDATE SET p.image64 = p1.image64
      WHEN NOT MATCHED THEN INSERT ( p.filename , p.image64)
                            VALUES ( p1.filename, p1.image64);
    commit;
end;
/

declare
    l_clob      clob;
    l_filename  varchar2(254);
begin
    l_clob := '/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDAAgGBgcGBQgHBwcJCQgKDBQNDAsLDBkSEw8UHRofHh0aHBwgJC4nICIsIxwcKDcpLDAxNDQ0Hyc5PTgyPC4zNDL/2wBDAQkJCQwLDBgNDRgyIRwhMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjL/wAARCAAkAFADASIAAhEBAxEB/8QAHwAAAQUBAQEBAQEAAAAAAAAAAAECAwQFBgcICQoL/8QAtRAAAgEDAwIEAwUFBAQAAAF9AQIDAAQRBRIhMUEGE1FhByJxFDKBkaEII0KxwRVS0fAkM2JyggkKFhcYGRolJicoKSo0NTY3ODk6Q0RFRkdISUpTVFVWV1hZWmNkZWZnaGlqc3R1dnd4eXqDhIWGh4iJipKTlJWWl5iZmqKjpKWmp6ipqrKztLW2t7i5usLDxMXGx8jJytLT1NXW19jZ2uHi4+Tl5ufo6erx8vP09fb3+Pn6/8QAHwEAAwEBAQEBAQEBAQAAAAAAAAECAwQFBgcICQoL/8QAtREAAgECBAQDBAcFBAQAAQJ3AAECAxEEBSExBhJBUQdhcRMiMoEIFEKRobHBCSMzUvAVYnLRChYkNOEl8RcYGRomJygpKjU2Nzg5OkNERUZHSElKU1RVVldYWVpjZGVmZ2hpanN0dXZ3eHl6goOEhYaHiImKkpOUlZaXmJmaoqOkpaanqKmqsrO0tba3uLm6wsPExcbHyMnK0tPU1dbX2Nna4uPk5ebn6Onq8vP09fb3+Pn6/9oADAMBAAIRAxEAPwD3+iignAyaACvPPGvxh8P+DNR/s2RJ73UFZfNhhGBEp5yzHjODnAz+FZnxY+Imq+HtAhu/DDWdxbyzPaz3yOJfs8o/h29M9eTnp0ryrX3b4kfD2PxMMSeIdDUQamABung/glwO45z/AMC9KAPqSzvINQsoLy1lWW3nQSRup4ZSMg1PXg/7P3jnz7aTwjfy5kiBlsWY9U6tH+HUexPpXvFABRRRQAUUUUAFeXeNvE+la/pkmlzweIYNKkvlsjqlgFSJ5Q20oSTkpnIJxgkcdK9Rrirz4aafeTbTq2rRaeLwXw06OVPIEu/ecAoTtLZO3OMk4xQB5KNP0nRPD0ulaZa61NoOvSOv2rUY0MLCON2EsO0hlbKqRuA3KPao9FsNL8F6PN4h0GHW9TlWwjjvXeJPsJeWNWMbrkMQNwJxnbxk9a9Zk+FumSi2hfV9ZNjaM5tbLz0MUAZWUhcpkgBjjJOPpST/AAq0uTTn02HV9ZtdPljiSe2gnQJM0aqodsocMQi5xgHHSgDy6y8K+ENG16y1jT/+EpjiXUEggv4I4zbCcuF2gn5igJK5xg4I5r1vwt4/tPF2qNBp9tOlssTyCWQKd2GC4O1iUPX5XAJFQy/DOwd4Yk1fVodNhvFvY9PjlTyVlDb+6FtpbJxnGScYq1onw/03RNfGspd3lzcpE8MXnlPlV23HJVQznPdyTigDraKKKACiiigAooooAKKKKACiiigAooooAKKKKAP/2Q==';
    l_filename := 'Adidas.jpg';

    MERGE INTO t_shp_ware_epl_image p
      USING ( SELECT l_clob     as image64
                   , l_filename as filename
                FROM dual
            ) p1 ON ( p.filename = p1.filename )
      WHEN MATCHED THEN UPDATE SET p.image64 = p1.image64
      WHEN NOT MATCHED THEN INSERT ( p.filename , p.image64)
                            VALUES ( p1.filename, p1.image64);
    commit;
end;
/

declare
    l_clob      clob;
    l_filename  varchar2(254);
begin
    l_clob := '/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDAAgGBgcGBQgHBwcJCQgKDBQNDAsLDBkSEw8UHRofHh0aHBwgJC4nICIsIxwcKDcpLDAxNDQ0Hyc5PTgyPC4zNDL/2wBDAQkJCQwLDBgNDRgyIRwhMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjL/wAARCAAPAFADASIAAhEBAxEB/8QAHwAAAQUBAQEBAQEAAAAAAAAAAAECAwQFBgcICQoL/8QAtRAAAgEDAwIEAwUFBAQAAAF9AQIDAAQRBRIhMUEGE1FhByJxFDKBkaEII0KxwRVS0fAkM2JyggkKFhcYGRolJicoKSo0NTY3ODk6Q0RFRkdISUpTVFVWV1hZWmNkZWZnaGlqc3R1dnd4eXqDhIWGh4iJipKTlJWWl5iZmqKjpKWmp6ipqrKztLW2t7i5usLDxMXGx8jJytLT1NXW19jZ2uHi4+Tl5ufo6erx8vP09fb3+Pn6/8QAHwEAAwEBAQEBAQEBAQAAAAAAAAECAwQFBgcICQoL/8QAtREAAgECBAQDBAcFBAQAAQJ3AAECAxEEBSExBhJBUQdhcRMiMoEIFEKRobHBCSMzUvAVYnLRChYkNOEl8RcYGRomJygpKjU2Nzg5OkNERUZHSElKU1RVVldYWVpjZGVmZ2hpanN0dXZ3eHl6goOEhYaHiImKkpOUlZaXmJmaoqOkpaanqKmqsrO0tba3uLm6wsPExcbHyMnK0tPU1dbX2Nna4uPk5ebn6Onq8vP09fb3+Pn6/9oADAMBAAIRAxEAPwD2fW7x08izt7pLa4nJYSMR8qrz39TtX6E1esLtb6yiuFGN68r/AHW6EfgciuV1/StV/tqLWIY1m2ExeVvA2ID8pGcck5J/Cr/2XXbXSL4WMcAvbkB4g7/LBKxwxPqAMNjucjvVyglBST3JT1aNe01jTb+8ubS0v7ae5tW2zxRShmiPTDAcjoetXa8Tvfhl4v0u81UaBfQOl/YQwPdo/wBmlMiyAsxwSdzKGy2eSxqn4a07xXrV3LrOlGY2drrU6myl1N/lWJAqLuOcruJLeuKzKPeKo6nrWl6NHG+p6ha2ayHahuJQm4+gz1rxy78A/EVtEtrGK/ZpkswPPGoMHE7SlnLMeSApwMe1bvxG8Da94jOkNpb3JutNtisN0LxY/wB6cAlgVLZ+Ucg96APTLK+tNStI7uyuIrm3kzsliYMrYODgj3BptrqNlfS3EdpdQzvbSGKdY3DGN/7rY6H2rwvR9F8W67qWp2drfXEh028tLGS7OoPH5XkqPPKqPvFj3Natr8PPGdpIL2zuEtL+4fULq8aO9YK8soIhUgcEDrnHBPtQB7TRXi8PgDxt/ZAt/wC0b6K4l+zQ3DHUTt2K26SRSDnecAdsg1av/h74nm8TXyW+o6hBo0jwizkg1NzJAg5c/O2ckk+uelAH/9k=';
    l_filename := 'Aquasphere.jpg';

    MERGE INTO t_shp_ware_epl_image p
      USING ( SELECT l_clob     as image64
                   , l_filename as filename
                FROM dual
            ) p1 ON ( p.filename = p1.filename )
      WHEN MATCHED THEN UPDATE SET p.image64 = p1.image64
      WHEN NOT MATCHED THEN INSERT ( p.filename , p.image64)
                            VALUES ( p1.filename, p1.image64);
    commit;
end;
/

declare
    l_clob      clob;
    l_filename  varchar2(254);
begin
    l_clob := '/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDAAgGBgcGBQgHBwcJCQgKDBQNDAsLDBkSEw8UHRofHh0aHBwgJC4nICIsIxwcKDcpLDAxNDQ0Hyc5PTgyPC4zNDL/2wBDAQkJCQwLDBgNDRgyIRwhMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjL/wAARCAAkAFADASIAAhEBAxEB/8QAHwAAAQUBAQEBAQEAAAAAAAAAAAECAwQFBgcICQoL/8QAtRAAAgEDAwIEAwUFBAQAAAF9AQIDAAQRBRIhMUEGE1FhByJxFDKBkaEII0KxwRVS0fAkM2JyggkKFhcYGRolJicoKSo0NTY3ODk6Q0RFRkdISUpTVFVWV1hZWmNkZWZnaGlqc3R1dnd4eXqDhIWGh4iJipKTlJWWl5iZmqKjpKWmp6ipqrKztLW2t7i5usLDxMXGx8jJytLT1NXW19jZ2uHi4+Tl5ufo6erx8vP09fb3+Pn6/8QAHwEAAwEBAQEBAQEBAQAAAAAAAAECAwQFBgcICQoL/8QAtREAAgECBAQDBAcFBAQAAQJ3AAECAxEEBSExBhJBUQdhcRMiMoEIFEKRobHBCSMzUvAVYnLRChYkNOEl8RcYGRomJygpKjU2Nzg5OkNERUZHSElKU1RVVldYWVpjZGVmZ2hpanN0dXZ3eHl6goOEhYaHiImKkpOUlZaXmJmaoqOkpaanqKmqsrO0tba3uLm6wsPExcbHyMnK0tPU1dbX2Nna4uPk5ebn6Onq8vP09fb3+Pn6/9oADAMBAAIRAxEAPwD3+iiub8WeMNM8NxQ2s5nuNRvcpaWNmN08xPHyjsP9o0AS6z438M+H7oW2q61Z2s5/5Zu+WH1Azj8a3Y5EljWSNg6OAyspyCD0Irwn4ha3fXGiw+Bh4ZttP1fWZYmghhnWcqhc5aQhRh8qOecgk54rtoPHFr4Pubfw7rmm3un2VtbmG01KTDRXIhjBOMcgkDgGgD0KiuC0v4kS6i+nyzeHbuxsb+fZb3N3MibotjP5m30wvT3zVGX4xWbN5tjoGq3dlPJ9nsLhECi9nzjZGDzjGTuPp0zQB6XRVPSru4vtKtrq6spLK4lQNJbSMGaI+hI4NXKACiiigANfIkXi/wAWn4qahq1hZm61yV5baOGSAymFScAKvbAGPzz1NfXdRJbQRzPMkMayv991UAt9T3oA8q8K+Atc0PT9W8XaxJ/aXjS4tZGgVyHEDbThR2LdBxwOg71wBXTdVj8OanqPiDV9WRLlE8Q2t7vK2byqUyFwNozuXjPQfSvpmojbQEyEwxnzPv5UfN9fWgD5quoNQ1u6tfC1hqE15pNrqE1lpN/Ou1jm3cNHnHzBSAM+h9MV1MmueGNT+HdnpGqXlxoHiLw5CronlsssE0S7QyjGGVjjj3/Gva1tLdBGFgiAjJZAEHyk9SPTqabLY2k8okmtoZJAMbnjBOPTJFAGN4H1W/1nwbpl7qqqmoyQKbhANpDdiR2JGDj3roaQADOB160tABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFAH//2Q==';
    l_filename := 'Asics.jpg';

    MERGE INTO t_shp_ware_epl_image p
      USING ( SELECT l_clob     as image64
                   , l_filename as filename
                FROM dual
            ) p1 ON ( p.filename = p1.filename )
      WHEN MATCHED THEN UPDATE SET p.image64 = p1.image64
      WHEN NOT MATCHED THEN INSERT ( p.filename , p.image64)
                            VALUES ( p1.filename, p1.image64);
    commit;
end;
/

declare
    l_clob      clob;
    l_filename  varchar2(254);
begin
    l_clob := '/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDAAgGBgcGBQgHBwcJCQgKDBQNDAsLDBkSEw8UHRofHh0aHBwgJC4nICIsIxwcKDcpLDAxNDQ0Hyc5PTgyPC4zNDL/2wBDAQkJCQwLDBgNDRgyIRwhMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjL/wAARCAAkAFADASIAAhEBAxEB/8QAHwAAAQUBAQEBAQEAAAAAAAAAAAECAwQFBgcICQoL/8QAtRAAAgEDAwIEAwUFBAQAAAF9AQIDAAQRBRIhMUEGE1FhByJxFDKBkaEII0KxwRVS0fAkM2JyggkKFhcYGRolJicoKSo0NTY3ODk6Q0RFRkdISUpTVFVWV1hZWmNkZWZnaGlqc3R1dnd4eXqDhIWGh4iJipKTlJWWl5iZmqKjpKWmp6ipqrKztLW2t7i5usLDxMXGx8jJytLT1NXW19jZ2uHi4+Tl5ufo6erx8vP09fb3+Pn6/8QAHwEAAwEBAQEBAQEBAQAAAAAAAAECAwQFBgcICQoL/8QAtREAAgECBAQDBAcFBAQAAQJ3AAECAxEEBSExBhJBUQdhcRMiMoEIFEKRobHBCSMzUvAVYnLRChYkNOEl8RcYGRomJygpKjU2Nzg5OkNERUZHSElKU1RVVldYWVpjZGVmZ2hpanN0dXZ3eHl6goOEhYaHiImKkpOUlZaXmJmaoqOkpaanqKmqsrO0tba3uLm6wsPExcbHyMnK0tPU1dbX2Nna4uPk5ebn6Onq8vP09fb3+Pn6/9oADAMBAAIRAxEAPwD3+iivO7b4qxTeJbvT5tIlhsIJbuFb7zgQz2y7pMpj5Rg8HNAHolFeTr8aJZPD51WPwrdMI7pbaeJrtFaMuqmI8jkNuOOONtatr8SNSuNR1O2fwrNHHpcRe9kN/EfKbyfM27erc/LlcjvQB6HRXlUXxoD6TcXUnhy4SdI7aaKEXcbCWOdtqncB8pz2I/KpV+MkOJY5tDniureC8kuITcKfLe3+8m4DBz6j9aAPUKK5S18bR3Wr+HdPFi6nWrFrxXMg/dAKDtIxz161lP8AFO1XxF4i0j+zZSdGtpZ/N80YnMYUsgGOD83v0oA9AorhvB3xDfxZcy2x0Se0mjiguObhJF8mUZVsjocfw4zXc0AFeSp4C8Ux3euWRnt/7Fvr27uGiin2tdLOFG18r8gUKc4OTmvWqKAPILn4Z6pJpN5a2tpZ20txNaysUmwjeQ2VBXHB2kjPfAz61LceBda/4TXxLqSaJYXEeprItvfPeFZIA0BTATGDk+tetUUAeE/8Ki1yHRJdOtra1SK5s7AXEYuMB7iKTMjH/gOeRXQeJ/hjK13HF4asba3sV0m9tdhlIJmmHBJOScnqSa9WooA8itvD/jq11LwzqI0PTWl0ezksjF/aBAdSqgPnbweDxWS/wv8AF66lc6kstrI982orNblwvlLOuFO/GWzxwemK9zooA86+HHgi/wDB9/cebDDDaz6dZo6RS7g1yiEStj3PfvXotFFABRRRQAUUUUAFFFFABRRRQAUUUUAf/9k=';
    l_filename := 'Caterpillar.jpg';

    MERGE INTO t_shp_ware_epl_image p
      USING ( SELECT l_clob     as image64
                   , l_filename as filename
                FROM dual
            ) p1 ON ( p.filename = p1.filename )
      WHEN MATCHED THEN UPDATE SET p.image64 = p1.image64
      WHEN NOT MATCHED THEN INSERT ( p.filename , p.image64)
                            VALUES ( p1.filename, p1.image64);
    commit;
end;
/

declare
    l_clob      clob;
    l_filename  varchar2(254);
begin
    l_clob := '/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDAAgGBgcGBQgHBwcJCQgKDBQNDAsLDBkSEw8UHRofHh0aHBwgJC4nICIsIxwcKDcpLDAxNDQ0Hyc5PTgyPC4zNDL/2wBDAQkJCQwLDBgNDRgyIRwhMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjL/wAARCAAkAFADASIAAhEBAxEB/8QAHwAAAQUBAQEBAQEAAAAAAAAAAAECAwQFBgcICQoL/8QAtRAAAgEDAwIEAwUFBAQAAAF9AQIDAAQRBRIhMUEGE1FhByJxFDKBkaEII0KxwRVS0fAkM2JyggkKFhcYGRolJicoKSo0NTY3ODk6Q0RFRkdISUpTVFVWV1hZWmNkZWZnaGlqc3R1dnd4eXqDhIWGh4iJipKTlJWWl5iZmqKjpKWmp6ipqrKztLW2t7i5usLDxMXGx8jJytLT1NXW19jZ2uHi4+Tl5ufo6erx8vP09fb3+Pn6/8QAHwEAAwEBAQEBAQEBAQAAAAAAAAECAwQFBgcICQoL/8QAtREAAgECBAQDBAcFBAQAAQJ3AAECAxEEBSExBhJBUQdhcRMiMoEIFEKRobHBCSMzUvAVYnLRChYkNOEl8RcYGRomJygpKjU2Nzg5OkNERUZHSElKU1RVVldYWVpjZGVmZ2hpanN0dXZ3eHl6goOEhYaHiImKkpOUlZaXmJmaoqOkpaanqKmqsrO0tba3uLm6wsPExcbHyMnK0tPU1dbX2Nna4uPk5ebn6Onq8vP09fb3+Pn6/9oADAMBAAIRAxEAPwD3+iq1/f2ml2Ut7fXMVtaxDdJLKwVVHuTXg+r/ABQ16/8AFkWr6NceXpdrJ5H2O4JjjjJGC1yenzc7ME9sc5BAPoGivNp/iBa+J9O0I6RcT2cF7qq2Oobvkmt/lZhGf7pcqAGHqcHNdHqtzZ+GJre5je4knvHjs4bNrhikju4AY7s4xnlvT1OKAOmorzvWvFFzH4rs7bY6z6ZLOZ4o5iIrhDaPKn6r0IOCPer1149ltrUzjSxIDp1pfqPPxkTybNp+X+Hrnv7UAdtRXFyeMb6O7mtbnSokSHU002aSK6JIMiKyOo2js65GRjnFc9aeLdR0jwLpyXtnPcJcaVLNFdRXpEzNENzBiVJUleQ3PIweooA9VornoPE3meKINGNuuJoJZFkWYMymPZkMBwMhxjnPHIGa6GgCrqOnWeradPYX9ulxazoUkicZDA14Xr/wk1mz1+003REF5o1ypiDXPKwJ1ZpyMF2GTs9MDHIr36igDkf+ETsNB8KJo+nacl5AzoJ0uEDvcKO7NjG4cYJGOMcdap20UV3axuPC/mpdiBDLI7v+7yGDZPKhD24OeRxzXdUiqFUKoAA6AUAcUto7zW87eF/MmEhdpGmfO50KMzFuW+UbTnPH5VBa6PaOkNqPCflCW3jibe8m1FQl1jLeisBjsD7V3tFAHEyWmIDcSaDPdXMzx3sylWTFyoAGOeqgDnpheCSRVb7Lax2tzpn/AAi2YxbsogVpOYmblUH8K7gMqMZ9Diu/pNq792BuxjOOcUAcbYW1vFrUV4PDbQTB5JFmUvvBbCuSDjO4KmfXqeRXZ0mBnOBnpmloAKKKKACiiigAooooAKKKKACiiigD/9k=';
    l_filename := 'Columbia.jpg';

    MERGE INTO t_shp_ware_epl_image p
      USING ( SELECT l_clob     as image64
                   , l_filename as filename
                FROM dual
            ) p1 ON ( p.filename = p1.filename )
      WHEN MATCHED THEN UPDATE SET p.image64 = p1.image64
      WHEN NOT MATCHED THEN INSERT ( p.filename , p.image64)
                            VALUES ( p1.filename, p1.image64);
    commit;
end;
/

declare
    l_clob      clob;
    l_filename  varchar2(254);
begin
    l_clob := '/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDAAgGBgcGBQgHBwcJCQgKDBQNDAsLDBkSEw8UHRofHh0aHBwgJC4nICIsIxwcKDcpLDAxNDQ0Hyc5PTgyPC4zNDL/2wBDAQkJCQwLDBgNDRgyIRwhMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjL/wAARCAAhAFADASIAAhEBAxEB/8QAHwAAAQUBAQEBAQEAAAAAAAAAAAECAwQFBgcICQoL/8QAtRAAAgEDAwIEAwUFBAQAAAF9AQIDAAQRBRIhMUEGE1FhByJxFDKBkaEII0KxwRVS0fAkM2JyggkKFhcYGRolJicoKSo0NTY3ODk6Q0RFRkdISUpTVFVWV1hZWmNkZWZnaGlqc3R1dnd4eXqDhIWGh4iJipKTlJWWl5iZmqKjpKWmp6ipqrKztLW2t7i5usLDxMXGx8jJytLT1NXW19jZ2uHi4+Tl5ufo6erx8vP09fb3+Pn6/8QAHwEAAwEBAQEBAQEBAQAAAAAAAAECAwQFBgcICQoL/8QAtREAAgECBAQDBAcFBAQAAQJ3AAECAxEEBSExBhJBUQdhcRMiMoEIFEKRobHBCSMzUvAVYnLRChYkNOEl8RcYGRomJygpKjU2Nzg5OkNERUZHSElKU1RVVldYWVpjZGVmZ2hpanN0dXZ3eHl6goOEhYaHiImKkpOUlZaXmJmaoqOkpaanqKmqsrO0tba3uLm6wsPExcbHyMnK0tPU1dbX2Nna4uPk5ebn6Onq8vP09fb3+Pn6/9oADAMBAAIRAxEAPwD0fx74+h8L28ltbyRLdiMSTTSgslqhJCkqCC7sQQqAjOCSQoJryzTGl+Iuk3uoyaxDHPBMcf2uv2nMKgF32ZEafeGAqYGMFu9Yep6fq/xL8Z2enWiuY7ojUb2XtEsp+UnPXZCI1Uex9TX0DZ6Pp/gzw7baRomnmTJaKKMuu92ILMzM3HYk9qAPHdf8M674ItW8Q6V9jvNEWKOUXVkpsrkK3tFhSBwcsCMEcGu4+HfxOj14QWd/cCbzm8qC7ZAj+bgnyplHAcgEqy/K+DwrAiumhMOq2Unhq6kj1MmxYahIZAdsjEAKdowucuQBggKMdq+W9Bt77RPGsujTLLbG4mayb5WGyTd+6cZ5ysgjYd+PegD7OorL8Oaoda8M6ZqjAK93axzMo6BmUEj881qUAFFFFABRRRQB82aJpHiTS/HEY0rUoLCOC0+yX5ulLxSGAmMoyDlsoEfjGFfORW1eeOrWx1qSwk8RWX2xVZby7jEiuz7sGJHdcRRjB+RcY4IcnNdn8Q/AT6yJtS0xJGnkUfaYYHCSsVGFliYkASAfKVJAdcAkEKR836l4J1mK/mjgP26QMS6g7LgHP8cL4kB/Aj0JoA928H63ZvNfw2L21xZTRKJWS68qNXG48su4lyoJ4GSFO7tUGtQeABJeXdpq8yapZyG8msLS6eVDPEQSGVh0Lqq54ySMda8S03w94osJ1KyyaRvON88/kk59FB3t0HCqTXt/w2+GT2kkeo6lHOIfNFwftS7ZryUHKs6nlI1PzBD8zNhmxgKAD0Tw0Lbw94a0TRr27t4byO0ijMTyqGZwoBwCcnnNbb3dtEzrJPErRqGcM4BUHgE+gr5xv7PR7XXvFkHjrQ9Yv9burwtp01qjkvGT8nlN0HbqDxxjjFbSeBbXxb8Yb611i21JNOi0e2k8uV2DMwjjUK7jqR82cHkqfegD3G61Gysdn2u8t4PMOE82VU3fTJ5qWWeGCBpppUjiUZZ3YBQPUk18+eIdM0bRfHmtx+MtG1C8002UcGhtEryIiKgUIpB4bgcnvknrmq93o/iC3+Gvgo+JLLUbjRbW9kk1G0QMZVgLDyt6jnAG/wBMZA44oA+h4r+zntDdxXcElsASZkkBQAdfmzikh1GxuYVmgvLeWJjtDpKrKT6ZBrwae08M3vgfxUNA0vxFp2kXVzajzRAZIdykkssRO4IMfNyTyv0rZ+Ddnaam+vxXOhWT2ivDsvIraSKG4IVhxFJwCAeSAOvPagD2k9K8S/aG/wCQXZf7rfzoooA5f9nz/kYZP+ubV9KiiigAo7UUUAFFFFABRRRQB//Z';
    l_filename := 'Crocs.jpg';

    MERGE INTO t_shp_ware_epl_image p
      USING ( SELECT l_clob     as image64
                   , l_filename as filename
                FROM dual
            ) p1 ON ( p.filename = p1.filename )
      WHEN MATCHED THEN UPDATE SET p.image64 = p1.image64
      WHEN NOT MATCHED THEN INSERT ( p.filename , p.image64)
                            VALUES ( p1.filename, p1.image64);
    commit;
end;
/

declare
    l_clob      clob;
    l_filename  varchar2(254);
begin
    l_clob := '/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDAAgGBgcGBQgHBwcJCQgKDBQNDAsLDBkSEw8UHRofHh0aHBwgJC4nICIsIxwcKDcpLDAxNDQ0Hyc5PTgyPC4zNDL/2wBDAQkJCQwLDBgNDRgyIRwhMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjL/wAARCAAkAFADASIAAhEBAxEB/8QAHwAAAQUBAQEBAQEAAAAAAAAAAAECAwQFBgcICQoL/8QAtRAAAgEDAwIEAwUFBAQAAAF9AQIDAAQRBRIhMUEGE1FhByJxFDKBkaEII0KxwRVS0fAkM2JyggkKFhcYGRolJicoKSo0NTY3ODk6Q0RFRkdISUpTVFVWV1hZWmNkZWZnaGlqc3R1dnd4eXqDhIWGh4iJipKTlJWWl5iZmqKjpKWmp6ipqrKztLW2t7i5usLDxMXGx8jJytLT1NXW19jZ2uHi4+Tl5ufo6erx8vP09fb3+Pn6/8QAHwEAAwEBAQEBAQEBAQAAAAAAAAECAwQFBgcICQoL/8QAtREAAgECBAQDBAcFBAQAAQJ3AAECAxEEBSExBhJBUQdhcRMiMoEIFEKRobHBCSMzUvAVYnLRChYkNOEl8RcYGRomJygpKjU2Nzg5OkNERUZHSElKU1RVVldYWVpjZGVmZ2hpanN0dXZ3eHl6goOEhYaHiImKkpOUlZaXmJmaoqOkpaanqKmqsrO0tba3uLm6wsPExcbHyMnK0tPU1dbX2Nna4uPk5ebn6Onq8vP09fb3+Pn6/9oADAMBAAIRAxEAPwD3+iiuD1X+29W+It1pFl4iu9LtLfTIbkJbwxPudpJFJO9SeiigDvKK5HQtV1PTteu/D2v3sV40VqL221AIIjJDu2sJFHyhlOORwQe1bL+ItNXUNMs0nEz6kJTbvCQ6N5a7mywOOhoA1aKpx6tp00Es8d/avFEdskizKVQ9ME54NNt9a0q6ljit9Ss5pJM7EjnVi2OuADzigC9RVJNX02SOSRNQtGSJtjss6kI3oTng+1Pg1KxupvJt7y3ll2B9kcqs209DgHp70AWqKKKAM/XLCfU9EvLG2u5LSaeIok8ZIZCfQjkfUc1w9roHi6xSRrCy0uznaH7OJZLyW6baCT/y0G4DJJA3HGeRnNekUUAeYP8ADbWNQ8N30Wp6tFLqstnBZW7AHy44YnD7GPVi5HzHHoAMCpNM+H2q2dzZ3Yls4JY5b6Z49xlRWmhVFwNqg8rlgAAa9LooA8jtfhfrB0XW7O5l06NtStLSHbGSUDQybmJARQAR0AHHT3rYk+HUyanLe2jWEEh1z+0Y2EWCsX2cx7OB/eOcdDXolFAHkFn8LNWIxfNphST7CJok+44gmLv8oRVAZSQFA46Z71r6F8OrrR/Gn9pb7Y2Ud3cXULxuVkxKuBGVC9B0+8RgDAFekUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAf//Z';
    l_filename := 'Delamare.jpg';

    MERGE INTO t_shp_ware_epl_image p
      USING ( SELECT l_clob     as image64
                   , l_filename as filename
                FROM dual
            ) p1 ON ( p.filename = p1.filename )
      WHEN MATCHED THEN UPDATE SET p.image64 = p1.image64
      WHEN NOT MATCHED THEN INSERT ( p.filename , p.image64)
                            VALUES ( p1.filename, p1.image64);
    commit;
end;
/

declare
    l_clob      clob;
    l_filename  varchar2(254);
begin
    l_clob := '/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDAAgGBgcGBQgHBwcJCQgKDBQNDAsLDBkSEw8UHRofHh0aHBwgJC4nICIsIxwcKDcpLDAxNDQ0Hyc5PTgyPC4zNDL/2wBDAQkJCQwLDBgNDRgyIRwhMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjL/wAARCAAoAFADASIAAhEBAxEB/8QAHwAAAQUBAQEBAQEAAAAAAAAAAAECAwQFBgcICQoL/8QAtRAAAgEDAwIEAwUFBAQAAAF9AQIDAAQRBRIhMUEGE1FhByJxFDKBkaEII0KxwRVS0fAkM2JyggkKFhcYGRolJicoKSo0NTY3ODk6Q0RFRkdISUpTVFVWV1hZWmNkZWZnaGlqc3R1dnd4eXqDhIWGh4iJipKTlJWWl5iZmqKjpKWmp6ipqrKztLW2t7i5usLDxMXGx8jJytLT1NXW19jZ2uHi4+Tl5ufo6erx8vP09fb3+Pn6/8QAHwEAAwEBAQEBAQEBAQAAAAAAAAECAwQFBgcICQoL/8QAtREAAgECBAQDBAcFBAQAAQJ3AAECAxEEBSExBhJBUQdhcRMiMoEIFEKRobHBCSMzUvAVYnLRChYkNOEl8RcYGRomJygpKjU2Nzg5OkNERUZHSElKU1RVVldYWVpjZGVmZ2hpanN0dXZ3eHl6goOEhYaHiImKkpOUlZaXmJmaoqOkpaanqKmqsrO0tba3uLm6wsPExcbHyMnK0tPU1dbX2Nna4uPk5ebn6Onq8vP09fb3+Pn6/9oADAMBAAIRAxEAPwD3+iua8ReP/DHhS8jtNY1SO3uZE8xYgrO23OMkAHHfr6VkJ8ZfAbuFGuKM9zBJ/wDE0Ad5RWIfF/h8eHJPEA1W3fS4/vXCNuAOcYwOc5IGMZrnD8Z/AYODrYB9Dbyf/E0Ad9RXHWvxS8H3mnXt/Dq6m2s9nnOYXGC5IUDjkkg8CtTw34w0PxZHcPot79pFuVWX92yFc5x94D0NAG7RXGXvxW8GWF/LZTayhmifY4iidwGzjGVBB/CtJ/HHh5PE8fhw6gDqrkKIFjY4JXdgkDAOOeaAOhorm9K8eeG9a1uXRrHUg+oRFwYXjdCSpwwG4DOKin+IvhaHWl0ddUFxfs+zybWJ5ju9PkBGfX0oA8Z1n4iW+sfFPzrnVntPDltKIz5UYczJHn0BPztx7LW54y8deHvFGgz6F4T0STUdQvMRh47DAiGeWBxnd6dMdc17MdI00kk6faEn/pgv+FWYbeG3TZDEka+iKFH6UAfKPiWOTw3pNj4Lmuo47gzi+1QhtyxyuAETjrsT5jjqW46Vu6drVtptjBYWXxJ0pIIhsjU+HWc/mUJJ+pr6Lm02xuJTJNZ28kh6s8Skn8SKaulacjh0sLVWU5BEKgg/lQB4P44efxV4z0XwFp0yyrbFDfTxwrGJJioLyMqgAbUzx6sRXO+Fv7fF94h8K+G2+zQ3NwRd3zkj7NbxF1JLdsg89zjA65r6hS1t452nSCNZn4aQIAx+p60JbQRmQpDGvmHL7VA3H1PrQB8peFLTTINY1HxIVaXQ9CHnRCXrcTZxAh7ZZvmI7AV0/wAO9T0vw6L/AMe+K7zN5evIllEBulnJOZXRfTPy54Awea+ghp9mtu1utpAIWOTGI12k+uMYobTrJ/L32du3ljCZiU7R6DjigD5f8aW2ua9Ld+O4dAl0jTZWVPM3kO2Rt8wjg4PAJGB065Jr2j4RWXhj/hD7bUdBs0jnkXy7uRzvlEo+8pb07gDAwRxXfSRRzRNFKivGwwysMgj0IptvbQWsfl28McKZztjQKPyFAEtFFFABRRRQAUUUUAFFFFABRRRQB//Z';
    l_filename := 'Demix.jpg';

    MERGE INTO t_shp_ware_epl_image p
      USING ( SELECT l_clob     as image64
                   , l_filename as filename
                FROM dual
            ) p1 ON ( p.filename = p1.filename )
      WHEN MATCHED THEN UPDATE SET p.image64 = p1.image64
      WHEN NOT MATCHED THEN INSERT ( p.filename , p.image64)
                            VALUES ( p1.filename, p1.image64);
    commit;
end;
/

declare

In [4]:
def remove_files(files):
    for i in files:
        i.unlink
remove_files(scaled_files)
print(scaled_files)

[WindowsPath('C:/projects/sm-code/shop/EXE2/Images/310 Motoring2.jpg'), WindowsPath('C:/projects/sm-code/shop/EXE2/Images/Adidas2.jpg'), WindowsPath('C:/projects/sm-code/shop/EXE2/Images/Aquasphere2.jpg'), WindowsPath('C:/projects/sm-code/shop/EXE2/Images/Asics2.jpg'), WindowsPath('C:/projects/sm-code/shop/EXE2/Images/Caterpillar2.jpg'), WindowsPath('C:/projects/sm-code/shop/EXE2/Images/Columbia2.jpg'), WindowsPath('C:/projects/sm-code/shop/EXE2/Images/Crocs2.jpg'), WindowsPath('C:/projects/sm-code/shop/EXE2/Images/Delamare2.jpg'), WindowsPath('C:/projects/sm-code/shop/EXE2/Images/Demix2.jpg'), WindowsPath('C:/projects/sm-code/shop/EXE2/Images/Everlast2.jpg'), WindowsPath('C:/projects/sm-code/shop/EXE2/Images/Fila2.jpg'), WindowsPath('C:/projects/sm-code/shop/EXE2/Images/Fischer2.jpg'), WindowsPath('C:/projects/sm-code/shop/EXE2/Images/Freddy2.jpg'), WindowsPath('C:/projects/sm-code/shop/EXE2/Images/Helly Hansen2.jpg'), WindowsPath('C:/projects/sm-code/shop/EXE2/Images/Joss2.jpg'), WindowsPath('C:/projects/sm-code/shop/EXE2/Images/Kappa2.jpg'), WindowsPath('C:/projects/sm-code/shop/EXE2/Images/Lotto2.jpg'), WindowsPath('C:/projects/sm-code/shop/EXE2/Images/Marc Ecko2.jpg'), WindowsPath('C:/projects/sm-code/shop/EXE2/Images/Merrell2.jpg'), WindowsPath('C:/projects/sm-code/shop/EXE2/Images/Mitre2.jpg'), WindowsPath('C:/projects/sm-code/shop/EXE2/Images/Mizuno2.jpg'), WindowsPath('C:/projects/sm-code/shop/EXE2/Images/New Balance2.jpg'), WindowsPath('C:/projects/sm-code/shop/EXE2/Images/Nike2.jpg'), WindowsPath('C:/projects/sm-code/shop/EXE2/Images/Nordway2.jpg'), WindowsPath('C:/projects/sm-code/shop/EXE2/Images/North Face2.jpg'), WindowsPath('C:/projects/sm-code/shop/EXE2/Images/ONeill2.jpg'), WindowsPath('C:/projects/sm-code/shop/EXE2/Images/Outventure2.jpg'), WindowsPath('C:/projects/sm-code/shop/EXE2/Images/Puma2.jpg'), WindowsPath('C:/projects/sm-code/shop/EXE2/Images/Reebok2.jpg'), WindowsPath('C:/projects/sm-code/shop/EXE2/Images/Reima2.jpg'), WindowsPath('C:/projects/sm-code/shop/EXE2/Images/Romika2.jpg'), WindowsPath('C:/projects/sm-code/shop/EXE2/Images/Rossignol2.jpg'), WindowsPath('C:/projects/sm-code/shop/EXE2/Images/Salomon2.jpg'), WindowsPath('C:/projects/sm-code/shop/EXE2/Images/Saucony2.jpg'), WindowsPath('C:/projects/sm-code/shop/EXE2/Images/Scubapro2.jpg'), WindowsPath('C:/projects/sm-code/shop/EXE2/Images/Skandia2.jpg'), WindowsPath('C:/projects/sm-code/shop/EXE2/Images/Skechers2.jpg'), WindowsPath('C:/projects/sm-code/shop/EXE2/Images/Sorel2.jpg'), WindowsPath('C:/projects/sm-code/shop/EXE2/Images/Speedo2.jpg'), WindowsPath('C:/projects/sm-code/shop/EXE2/Images/Technisub2.jpg'), WindowsPath('C:/projects/sm-code/shop/EXE2/Images/Tecnica2.jpg'), WindowsPath('C:/projects/sm-code/shop/EXE2/Images/Termit2.jpg'), WindowsPath('C:/projects/sm-code/shop/EXE2/Images/timberland2.jpg'), WindowsPath('C:/projects/sm-code/shop/EXE2/Images/tusa2.jpg'), WindowsPath('C:/projects/sm-code/shop/EXE2/Images/Umbro2.jpg'), WindowsPath('C:/projects/sm-code/shop/EXE2/Images/Victor2.jpg'), WindowsPath('C:/projects/sm-code/shop/EXE2/Images/View2.jpg'), WindowsPath('C:/projects/sm-code/shop/EXE2/Images/Wilson2.jpg'), WindowsPath('C:/projects/sm-code/shop/EXE2/Images/Авантаж2.jpg')]